# for development

version: '3.2'

services:
    backend:
        container_name: flights-api
        build:
            dockerfile: api.Dockerfile
        command: bash -c "composer install && chmod +x /usr/bin/wait_for_mysql.sh && /usr/bin/wait_for_mysql.sh && php artisan migrate:fresh --seed && php artisan serve --host 0.0.0.0"
        working_dir: /usr/src/app
        env_file: .env
        ports:
            - ${BACKEND_PORT}:8000
        expose:
            - ${BACKEND_PORT}
        volumes:
            - ./scripts/wait_for_mysql.sh:/usr/bin/wait_for_mysql.sh
            - ./backend:/usr/src/app
            - /usr/src/app/vendor
        depends_on:
            - mysql

    mysql:
        container_name: flights-db
        image: mariadb:10
        restart: always
        ports:
            - "3307:3306"
        volumes:
            - ./.docker-data/db_data:/var/lib/mysql
        environment:
            - MARIADB_RANDOM_ROOT_PASSWORD=yes
            - MARIADB_DATABASE=${DB_NAME}
            - MARIADB_PASSWORD=${DB_PASS}
            - MARIADB_USER=${DB_USER}

    frontend:
        container_name: flights-web
        image: node:16
        command: bash -c "npm i --no-update-notifier && npm run dev -- --host 0.0.0.0"
        working_dir: /usr/src/app
        env_file: .env
        ports:
            - ${FRONTEND_PORT}:${FRONTEND_PORT}
        expose:
            - ${FRONTEND_PORT}
        volumes:
            - ./frontend:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            - backend
